CREATE TABLE `person` (
    `Id` int UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `FirstName` VARCHAR(50) NULL DEFAULT NULL,
	`LastName` VARCHAR(50) NULL DEFAULT NULL,
    `Email` VARCHAR(50) NULL DEFAULT NULL,
    `PassWord` VARCHAR(50) NULL DEFAULT NULL
)ENGINE = InnoDB;